<a href="https://colab.research.google.com/github/afjal6000/NumPy-mini-project/blob/main/NumPy_first_projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY MINI PROJECT
######Let us build a mini project to learn more about NumPy.
Features of the data set:

*   Age: Age of the Person
*   education-num: No. of years of education they had 
*   race: Person's race
          0 - Amer-Indian-Eskimo
          1 - Asian-Pac-Islander
          2 - Black
          3 - Other
          4 - White
*   sex: Person's gender
          0 - Female
          1 - Male
*   capital-gain: Income from investment sources, apart from wages/salary
*   capital loss: Losses from investment sources, apart from wages/salary
*   hours-per-week: No. of hours per week the person works
*   income: Annual Income of the person
          0 - Less than or equal to 50k
          1 - More than 50k











#Step 1 : Importing Numpy:

In [ ]:
import numpy as np

#Step 2 : Read the Data!
###### For reading the data 1st we need to upload the data set into our google colab. After that we can just save the copy data path link or the name of the data set into a variable.



In [ ]:
data_file = '/content/makeSenseOfCensus (1).csv'

######In here we are saving data path of the data set in a variable called 'data_file' successfully. After this we need to load the data.

##Loading the data:

In [ ]:
data = np.genfromtxt(data_file, delimiter = ',', skip_header = 1)
#printing the data
print('\nData: \n\n', data)
#printing the data type of data
print('\nData: \n\n', type(data))


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Data: 

 <class 'numpy.ndarray'>


#Step 2 : Append the Data:
######We are going to append 'new_record'(given) to 'data' using 'np.concatenate()'. Let's check who that will work.

In [ ]:
new_record = [[50,9,4,1,0,0,40,0]]
#Appending the 'new_record' data with the 'data'
append_data = np.concatenate((data, new_record))
#Lets check the new data added or not..
append_data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

#Step 3 : Check if it's a young country or old country..

- Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

- Find the max age and store it in a variable called 'max_age'.

- Find the min age and store it in a variable called 'min_age'.

- Find the mean of the age and store it in a variable called 'age_mean'.

- Find the standard deviation of the age and store it in a variable called 'age_std'

######Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [ ]:
age = append_data[:,0]
#printing the age..
print("Age of all the person's-", age)

Age of all the person's- [39. 50. 38. ... 40. 39. 50.]


######Find the max age and store it in a variable called 'max_age'.

In [ ]:
max_age = age.max()
#printing the max_age..
print("Maximum age of a person present in the data set is -", max_age)

Maximum age of a person present in the data set is - 90.0


######Find the min age and store it in a variable called 'min_age'.

In [ ]:
min_age = age.min()
# printing the min_age..
print("Minimum age of a person present in the data set is -", min_age)

Minimum age of a person present in the data set is - 17.0


######Find the mean of the age and store it in a variable called 'age_mean'.

In [ ]:
age_mean = age.mean()
# printing the age_mean
print("The mean of the age is -", age_mean)

The mean of the age is - 38.06293706293706


######Find the standard deviation of the age and store it in a variable called 'age_std'

In [ ]:
age_std = age.std()
# printing the age_std
print("The standard deviation of the age is -", age_std)

The standard deviation of the age is - 13.341478176165857


# Step 4: Let's check the country's race distribution to identify the minorities
- Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

- Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

- Find out which is the race with the minimum no. of citizens

- Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

######Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [ ]:
race = append_data[:,2]
# printing the race
print(race)

[4. 4. 4. ... 4. 4. 4.]


In [ ]:
# storing the "0 - Amer-Indian-Eskimo" in a new veriable called 'race_0'
race_0 = race[race==0]
print(race_0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# storing the "1 - Asian-Pac-Islander" in a new veriable called 'race_1'
race_1 = race[race==1]
print(race_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]


In [ ]:
# storing the "2 - Black" in a new veriable called 'race_2'
race_2 = race[race==2]
print(race_2)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [ ]:
# storing the "3 - other" in a new veriable called 'race_3'
race_3 = race[race==3]
print(race_3)

[3. 3. 3. 3. 3. 3.]


In [ ]:
# storing the "4 - white" in a new veriable called 'race_4'
race_4 = race[race==4]
print(race_4)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.

#####Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [ ]:
len_0 = len(race_0)
print("The length of race_0 is -", len_0)
len_1 = len(race_1)
print("The length of race_1 is -", len_1)
len_2 = len(race_2)
print("The length of race_2 is -", len_2)
len_3 = len(race_3)
print("The length of race_3 is -", len_3)
len_4 = len(race_4)
print("The length of race_4 is -", len_4)

The length of race_0 is - 10
The length of race_1 is - 27
The length of race_2 is - 110
The length of race_3 is - 6
The length of race_4 is - 848


######Find out which is the race with the minimum no. of citizens

In [ ]:
min_len = [len_0,len_1,len_2,len_3,len_4,]
print('the race with the minimum no. of citizens is race_3 which have only -',np.min(min_len), 'person.')
min_len

the race with the minimum no. of citizens is race_3 which have only - 6 person.


[10, 27, 110, 6, 848]

######Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
min_arr = np.array(min_len)
min_arr
minority_race = np.argwhere(min_arr==6)
print(minority_race)

[[3]]


###### Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place
- Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

- Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

- Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

- Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

- Print 'avg_working_hours' and see if the govt. policy is followed.


######Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

In [ ]:
senior_citizens = age[age > 60]
#printing the senior_citizens
print(senior_citizens)

[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]


######Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [ ]:
# extracting hours-per-week column and saving it in a new veriable called 'working_hour"
working_hour = append_data[:,6]
working_hour
# Adding all the working hours of senior_citizens 
working_hour_sum = np.sum(working_hour[age>60])
print("The working hour sum of all the senior citizens is -", working_hour_sum)

The working hour sum of all the senior citizens is - 1917.0


######Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [ ]:
senior_citizens_len = len(senior_citizens)
print("The length of 'senior_citizens' is -", senior_citizens_len)

The length of 'senior_citizens' is - 61


######Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.


In [ ]:
avg_working_hours = working_hour_sum/senior_citizens_len

###### Print 'avg_working_hours' and see if the govt. policy is followed.

In [ ]:
print("The average working hours of the senior citizens is -", avg_working_hours)
if avg_working_hours < 25:
  print("The govt. policy is followed.")
else:
  print("The govt. policy is not followed")


The average working hours of the senior citizens is - 31.42622950819672
The govt. policy is not followed


###### Step 6: Let's check that higher educated people have better pay in general.

- Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.

- Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.




In [ ]:
# extracting education column
education = append_data[:,1]
education


array([13., 13.,  9., ..., 10., 13.,  9.])

######Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.

In [ ]:
high = education[education > 10]
low = education[education <= 10]

######Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [ ]:
# extracting 'income' coloum
income = append_data[:,7]
print("The mean of income column is -", np.mean(income))
avg_pay_high = np.mean(income[education > 10])
print("The mean of income column of 'high' is -", avg_pay_high)
avg_pay_low = np.mean(income[education <= 10])
print("The mean of income column of 'low' is -", avg_pay_low)

The mean of income column is - 0.23176823176823177
The mean of income column of 'high' is - 0.42813455657492355
The mean of income column of 'low' is - 0.13649851632047477
